### PR TITLE
Update Q&A.md

### PR DESCRIPTION
**Pull request by blabla1337**
please review, added a question and added some text + links for example recovery mechanism

### CODE REVIEW

**Comment by joshbressers** [comment]
I wonder if putting much of this content in the guide would make more sense
https://github.com/ossf/great-mfa-project/blob/main/guide/key-usage-guide.md

I think keeping important details close together will improve the quality of life for the users.

**Review by SecurityCRob — APPROVED** [review]
+1

**Comment by david-a-wheeler** [comment]
Hmm, merge conflict & Josh B. has a question. Thoughts?

**Comment by SecurityCRob** [comment]
I agree with bressers, I'd rather have all the useful info nearby, less chance of losing people clicking around.

**Comment by david-a-wheeler** [comment]
@blabla1337 - could you do that instead?

**Pull request closed without merging**
